# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapp.proto\x12\x03\x61pp\"\x92\x01\n\rClientRequest\x12$\n\ntext_input\x18\x01 \x01(\x0b\x32\x0e.app.TextInputH\x00\x12$\n\nimage_path\x18\x02 \x01(\x0b\x32\x0e.app.ImagePathH\x00\x12*\n\rtrain_command\x18\x03 \x01(\x0b\x32\x11.app.TrainCommandH\x00\x42\t\n\x07request\"\x19\n\tTextInput\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x19\n\tImagePath\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1d\n\x0cTrainCommand\x12\r\n\x05start\x18\x01 \x01(\x08\"\x8e\x01\n\x0eServerResponse\x12$\n\nimage_data\x18\x01 \x01(\x0b\x32\x0e.app.ImageDataH\x00\x12#\n\x06status\x18\x02 \x01(\x0b\x32\x11.app.StatusUpdateH\x00\x12%\n\x07message\x18\x03 \x01(\x0b\x32\x12.app.ServerMessageH\x00\x42\n\n\x08response\"6\n\tImageData\x12\x13\n\x0bimage_bytes\x18\x01 \x01(\x0c\x12\x14\n\x0cimage_format\x18\x02 \x01(\t\"\x1e\n\x0cStatusUpdate\x12\x0e\n\x06status\x18\x01 \x01(\t\" \n\rServerMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\nAppService\x12:\n\x0b\x43ommunicate\x12\x12.app.ClientRequest\x1a\x13.app.ServerResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLIENTREQUEST']._serialized_start=19
  _globals['_CLIENTREQUEST']._serialized_end=165
  _globals['_TEXTINPUT']._serialized_start=167
  _globals['_TEXTINPUT']._serialized_end=192
  _globals['_IMAGEPATH']._serialized_start=194
  _globals['_IMAGEPATH']._serialized_end=219
  _globals['_TRAINCOMMAND']._serialized_start=221
  _globals['_TRAINCOMMAND']._serialized_end=250
  _globals['_SERVERRESPONSE']._serialized_start=253
  _globals['_SERVERRESPONSE']._serialized_end=395
  _globals['_IMAGEDATA']._serialized_start=397
  _globals['_IMAGEDATA']._serialized_end=451
  _globals['_STATUSUPDATE']._serialized_start=453
  _globals['_STATUSUPDATE']._serialized_end=483
  _globals['_SERVERMESSAGE']._serialized_start=485
  _globals['_SERVERMESSAGE']._serialized_end=517
  _globals['_APPSERVICE']._serialized_start=519
  _globals['_APPSERVICE']._serialized_end=591
# @@protoc_insertion_point(module_scope)
